- name: creating roboshop user
  user:
   name: roboshop
- name: delete /app folder
  file:
   path: /app
   state: absent
- name: creating folder
  file: 
   path: /app
   state: directory
- name: Download the {{component}} file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /tmp/catalogue.zip

- name: Change directory to /app
  ansible.builtin.command:
    cmd: cd /app
- name: Unzip the {{component}}.zip file
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
- name: install npm
  ansible.builtin.shell: npm install
  args:
    chdir: /app
